// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AlignCommentsExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AlignCommentsExtension.277a8d42-8e31-48f0-9a2d-dca731e08c8f";
        public const string Name = "Align Comments";
        public const string Description = @"Align single-line comments for C, C++, C# and JavaScript";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Lixfeld";
        public const string Tags = "align, alignment, comment, formatting";
    }
}
